### ISSUE TITLE
EGK with URCaps, the configuration for host ip and custom port 

### ISSUE THREAD

**Issue by 0707yiliu** [SCHUNK-SE-Co-KG/bkstools#1]
Hi, I try to equip the gripper EGK_40_M_B on UR3e, and I can control the schunk gripper on the ur-polyscope with urcaps.

But I want to communicate with the gripper by python programe. 

The recommend command is:
`bks -H 10.42.0.162 --list`
and the error I got is:
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.42.0.162', port=80): Max retries exceeded with url: /adi/info.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41d8466640>: Failed to establish a new connection: [Errno 111] Connection refused'))`

I have tried to change the host ip, custom port annd host name in URCap's External Control:
![signal-2024-01-04-170335_002](https://github.com/SCHUNK-SE-Co-KG/bkstools/assets/28921533/fd6e9539-01d6-417b-beed-2ff469579f2f)
the raw datas were host ip:10.42.0.1, custom port:50002, host name: 10.42.0.1. Both of the configurations were failed.

Do you know how to configure the Schunk with URCaps? OR why is port 80 in this error?

________________________________________________

Update, I found that the EGK_40_MB communicates to the robot with ModBus-RTU, but the bkstools need to get the COM or /dev/ttyUSB to setup the ModBus-RTU, I can not find the port on my laptop, do you know how to solve it? 

Thank you!

**Comment by DirkOsswald** [comment]
Hello. 
As you already found out you have a EGK-40-MB (Modbus-RTU), So I guess your setup looks something like this:

```
________                         ______________________                             _____________
|Laptop|_________________________| UR-Robot-controller|_____________________________|EGK-40-MB-*|
|______|    (Ethernet/TCP/IP)    |____________________|       (RS485/Modbus-RTU)    |___________|
```

And you want to use the BKSTools run by a Python-Interpreter on your Laptop, right?

If this is the case then - unfortunately - I have to say that this will not work. Although the BKSTools are able to use eithter Ethernet/TCP/IP or RS485/Modbus-RTU, but only if connected directly to the gripper. In your setup the UR-Robot-controller would have to gateway between Ethernet/TCP/IP on the one side and RS485/Modbus-RTU on the other side - which it simply does not do.

Even if you somehow mangage to get the BKSTools to run on the UR-Robot-controller (unlikely, but I'm not an UR-expert), it would still not work IMHO: Opposed to TCP/IP based interfaces a serial port like RS485 (available as COMx on Windows like systems or /dev/ttyS* or /dev/ttyUSB* on Unix like systems) cannot be shared beteween multiple applications. And since the UR control system and therein the SCHUNK UR-Plugin do have (exclusive) access to the serial port, an additional Python Interpreter running the BKSTools would not get access to that port.

Sorry.

**Comment by 0707yiliu** [comment]
> Hello. As you already found out you have a EGK-40-MB (Modbus-RTU), So I guess your setup looks something like this:
> 
> ```
> ________                         ______________________                             _____________
> |Laptop|_________________________| UR-Robot-controller|_____________________________|EGK-40-MB-*|
> |______|    (Ethernet/TCP/IP)    |____________________|       (RS485/Modbus-RTU)    |___________|
> ```
> 
> And you want to use the BKSTools run by a Python-Interpreter on your Laptop, right?
> 
> If this is the case then - unfortunately - I have to say that this will not work. Although the BKSTools are able to use eithter Ethernet/TCP/IP or RS485/Modbus-RTU, but only if connected directly to the gripper. In your setup the UR-Robot-controller would have to gateway between Ethernet/TCP/IP on the one side and RS485/Modbus-RTU on the other side - which it simply does not do.
> 
> Even if you somehow mangage to get the BKSTools to run on the UR-Robot-controller (unlikely, but I'm not an UR-expert), it would still not work IMHO: Opposed to TCP/IP based interfaces a serial port like RS485 (available as COMx on Windows like systems or /dev/ttyS* or /dev/ttyUSB* on Unix like systems) cannot be shared beteween multiple applications. And since the UR control system and therein the SCHUNK UR-Plugin do have (exclusive) access to the serial port, an additional Python Interpreter running the BKSTools would not get access to that port.
> 
> Sorry.

Hi, @DirkOsswald ,
many thanks for your reply. 
I have check the version we got, just like I said the version of schunk is  EGK_40_MB and can only use ModBus-RTU to communicate with user.

So I make 2 plans for the  EGK_40_MB.
1. using BKStools, the connection method be like:  EGK_40_MB---(4 Pin Aviation Connector to RS485)---(RS485-USB)---Laptop, this method does not make connection between EGK and RobotArm
2. without BKStools, connect to the ur-e with urcap, and make communication via modbus-RTU through URCap port.
I think the first one follows the principles required by BKStools, if there are any errors, please tell me.
Is the second one feasible? Because it will make the robot arm look cleaner (no extra cable).
Thank you!

**Comment by DirkOsswald** [comment]
Hi, you are welcome.
 
> So I make 2 plans for the EGK_40_MB.
> 
>     1. using BKStools, the connection method be like:  EGK_40_MB---(4 Pin Aviation Connector to RS485)---(RS485-USB)---Laptop, this method does not make connection between EGK and RobotArm
> 
>     2. without BKStools, connect to the ur-e with urcap, and make communication via modbus-RTU through URCap port.
>        I think the first one follows the principles required by BKStools, if there are any errors, please tell me.
>        Is the second one feasible? Because it will make the robot arm look cleaner (no extra cable).
>        Thank you!

This approach requires re-cabeling / re-plugging depending on which "plan" you want to use. But yes, if this is feasible for you then this will definetly work.

One more tip: If you want to access the RS485 adapter from Linux then you might have to add your user to the "dialout" group in order to be able to access character devices like /dev/ttyS* or /dev/ttyUSB*. Most Linux systems also need a real reboot before changes in group-membership gets effective - simple logout/login might not be sufficient.

**Comment by 0707yiliu** [comment]
> This approach requires re-cabeling / re-plugging depending on which "plan" you want to use. But yes, if this is feasible for you then this will definetly work.
> 
> One more tip: If you want to access the RS485 adapter from Linux then you might have to add your user to the "dialout" group in order to be able to access character devices like /dev/ttyS* or /dev/ttyUSB*. Most Linux systems also need a real reboot before changes in group-membership gets effective - simple logout/login might not be sufficient.

Hi, @DirkOsswald,
I will try the first method anyway, thanks for confirming it.
I'm also interested to know what the second approach looks like. Can it communicate via URcap? Since I didn't find the appropriate port in the [open ports list](https://forum.universal-robots.com/t/overview-of-used-ports-on-local-host/8889), I'm not sure if it's possible. If possible, is there a command set for ModBus-RTU in BKSTools? Is it possible to communicate using BKStools?

Thank you!

**Comment by DirkOsswald** [comment]
I don't understand your last couple of questions.
With  "_second approach_" you mean "_without BKStools, connect to the ur-e with urcap, and make communication via modbus-RTU through URCap port_", right?
As said, I'm not a UR-Expert but to my knowledge what the (SCHUNK) URCap does here is that it controls a SCHUNK EGK gripper (that is connected via RS485/Modbus-RTU to to the robot-controller) within the UR-"PolyScope" programming environment. The open port list seems to be the list of TCP/UDP ports used by the PolyScope + URCaps on the Ethernet side of the Robot controlller. 
In this second setup there is no way for the BKSTools to interact with the SCHUNK EGK gripper. The RS485/Modbus-RTU interface is allready occupied by the SCHUNK URCap and the TCP/UDP ports of the robot controller do not have any connection to the EGK.

**Comment by 0707yiliu** [comment]
> I don't understand your last couple of questions. With "_second approach_" you mean "_without BKStools, connect to the ur-e with urcap, and make communication via modbus-RTU through URCap port_", right? As said, I'm not a UR-Expert but to my knowledge what the (SCHUNK) URCap does here is that it controls a SCHUNK EGK gripper (that is connected via RS485/Modbus-RTU to to the robot-controller) within the UR-"PolyScope" programming environment. The open port list seems to be the list of TCP/UDP ports used by the PolyScope + URCaps on the Ethernet side of the Robot controlller. In this second setup there is no way for the BKSTools to interact with the SCHUNK EGK gripper. The RS485/Modbus-RTU interface is allready occupied by the SCHUNK URCap and the TCP/UDP ports of the robot controller do not have any connection to the EGK.

Okido, I understand, this question could be closed, thank you for your reply!
