### ISSUE TITLE
the activation problem of ModBus RTU

### ISSUE THREAD

**Issue by 0707yiliu** [SCHUNK-SE-Co-KG/bkstools#3]
Hi, we had used the interpreter mode of UR to control the schunk-EGK-40M remotely, but this method needed to clean the UR's buffer, which made that the controlling speed of schunk just had 5hz. Hence, we want to use modbus RTU (RS485) protocol to control the schunk. 
 
this was our connection method, the power was supported by UR control box (24V)
![signal-2024-05-01-140809_002](https://github.com/SCHUNK-SE-Co-KG/bkstools/assets/28921533/2d64e133-fa46-4b5b-a8f2-aff35488b15a)

BUT we got the wrong light from schunk. The light from schunk proves that our powerline wiring was correct, but the COM light was inactivate, (we have exchanged the BUS-A and BUS-B for testing, getting the same light problem)
Do you know how to test it or solve it? Many thanks!
![signal-2024-05-01-140812_002](https://github.com/SCHUNK-SE-Co-KG/bkstools/assets/28921533/2f1db406-d5ac-4f84-b86a-11f4a7636ea5)

**Comment by 0707yiliu** [comment]
this is the normal situation, but my device's ID is 14 and the default is 12, which leads to the program can not find the device, I changed the ID and it works

**Comment by BrocoliAsesino** [comment]
Hello @0707yiliu, 

I am having a similar issue however, cannot find the correct slave id for the gripper (not sure if this is where the issue comes from). 
I am using an EGU Schunk 60 MB-M-B gripper and did the installation throught pip. 

Thanks in advance!
